## Read the CSV files
Paris_listing <- read_csv(gzfile("data/original datasets/Paris_listing.csv.gz"), col_names = TRUE)
View(Paris_listing)
Paris_calendar <- read_csv(gzfile("data/original datasets/Paris_calendar.csv.gz"), col_names = TRUE)
View(Paris_calendar)
Amsterdam_listing <- read_csv(gzfile("data/original datasets/Amsterdam_listing.csv.gz"), col_names = TRUE)
View(Amsterdam_listing)
Amsterdam_calendar <- read_csv(gzfile("data/original datasets/Amsterdam_calendar.csv.gz"), col_names = TRUE)
View(Amsterdam_calendar)
NY_listing <- read_csv(gzfile("data/original datasets/NY_listing.csv.gz"), col_names = TRUE)
View(NY_listing)
NY_calendar <- read_csv(gzfile("data/original datasets/NY_calendar.csv.gz"), col_names = TRUE)
View(NY_calendar)
